import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mainSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Or create a sidebar manually
  mainSidebar: [
    // 'index',
    {
      type: 'doc',
      id: 'index',
      label: 'Start',
    },
    {
      type: 'doc',
      id: 'setup',
    },
    {
      type: 'category',
      label: 'WordPress',
      // link: {
      //   type: 'doc',
      //   id: 'wordpress',
      // },
      collapsed: false,
      // collapsible: false,
      items: [
        // { type: 'autogenerated', dirName: 'components' }
        {
          type: 'doc',
          id: 'wordpress/create',
          // label: 'Site',
        },
        {
          // type: 'doc',
          // id: 'wordpress/plugin',
          type: 'category',
          label: 'Plugin',
          collapsed: false,
          collapsible: false,
          items: [{ type: 'autogenerated', dirName: 'wordpress/plugin' }],
        },
        {
          type: 'doc',
          id: 'wordpress/theme',
          label: 'Theme',
        },
      ],
    },

    {
      type: 'html',
      value: `<hr>`,
      // `<hr><div class="sidebar-section-title">Modules</div>`,
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      // collapsible: false,
      items: [
        { type: 'autogenerated', dirName: 'modules' },
        // {
        //   type: 'doc',
        //   id: 'modules/framework',
        // },
        // {
        //   type: 'doc',
        //   id: 'modules/pipeline',
        // },
        // {
        //   type: 'doc',
        //   id: 'modules/updater',
        // },
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'plugins' }],
    },
    {
      type: 'html',
      value: `<hr>`,
      // `<hr><div class="sidebar-section-title">Server</div>`,
    },

    // {
    //   type: 'doc',
    //   id: 'server',
    //   label: 'Server',
    // },
    {
      type: 'category',
      label: 'Server',
      collapsed: false,
      // collapsible: false,
      items: [
        {
          type: 'doc',
          id: 'server/docker',
        },
        {
          type: 'doc',
          id: 'server/nginx',
        },
        {
          type: 'doc',
          id: 'server/https',
        },

        // items: [
        //   {
        //     type: 'doc',
        //     id: 'server/docker',
        //   },
        // ]
      ],
    },
    {
      type: 'html',
      value: `<hr>`,
      // `<hr><div class="sidebar-section-title">Guides</div>`,
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      // collapsible: false,
      items: [
        {
          type: 'doc',
          id: 'guides/plugin-upgrade',
        },
        {
          type: 'doc',
          id: 'guides/github-pages',
        },
        {
          type: 'doc',
          id: 'guides/types-of-documentation',
          label: 'Types of documentation',
        },
      ],
    },

  ],
}

export default sidebars
